version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=geekprofile
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=geekprofile
    ports:
      - "3306:3306"
    volumes:
      - /opt/homebrew/var/mysql:/var/lib/mysql   # ‚Üê bind mount vers ton datadir local

